version: 2.1

jobs:
  install-dependencies:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run:
          name: Update or install NPM
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: app-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - persist_to_workspace:
          root: .
          paths:
            - .
  vercel-deploy:
    build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run:
          name: Install CLI Vercel
          command: 'sudo npm install -g vercel'
      - attach_workspace:
          at: .
      - run:
          name: Vercel Prod Deploy
          command: "vercel --force --with-cache --prod -n $VERCEL_PROJECT_NAME --token=$VERCEL_TOKEN --yes --build-env MONGODB_URL='mongodb+srv://jcvaldes:mlEUVkBHfZn5Xmjt@cluster0.kgn4b.mongodb.net/shoppay?retryWrites=true&w=majority' --build-env NEXTAUTH_SECRET='y.m>#U>L+et4VG+WJh]mbPt' --build-env NEXTAUTH_URL='https://devkingos-shopay-dev.vercel.app' --build-env BASE_URL='https://devkingos-shopay-dev.vercel.app' --build-env GITHUB_ID='06700db5d5ca13912b8d' --build-env GITHUB_SECRET='5e818f4bd941a7b0a2acb4c7ec44bf9c938bb9f3' --build-env GOOGLE_ID='819111550272-d5qkblbg09e7bqce5h06hdpfbcq7p5ss.apps.googleusercontent.com' --build-env GOOGLE_SECRET='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' --build-env TWITTER_ID='o3rjJPF0mwq5mWGVa45VjXbrt' --build-env TWITTER_SECRET='sg9Kc8tWW82GbLVnlgfkbgmQvPQLWuIQePLqA6og2t3e2ov7g0' --build-env T_ID='TW8tNnphNEpUNHJEZDBuT0hYQVo6MTpjaQ' --build-env T_SECRET='a1JCUGEdH09VSI1_Ym_m3-wkocLHL99nXiVtjvbwJGjdUVzJ3x' --build-env AUTH0_CLIENT_ID='5YkIFgLUjJxVN4bNlqg6SVs3l8DlS5o8' --build-env AUTH0_CLIENT_SECRET='ao4CwtqSAwrbrGZb6JPjXZs-VvmTnLS-ARkaOLKLdwp5_I8sNoGcG_ttYRwzusA9' --build-env AUTH0_ISSUER='https://dev-clggp3124ua5o1j8.us.auth0.com' --build-env ACTIVATION_TOKEN_SECRET='j+#U>L+et4VG+WJh]mbPt482hjrkfdREW@Sdsa'"

workflows:
  version: 2
  deploy-reactapp:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - develop
      - vercel-deploy:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - develop
