version: 2.1

jobs:
  install-dependencies:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run:
          name: Update or install NPM
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: app-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - persist_to_workspace:
          root: .
          paths:
            - .
  vercel-deploy:
    build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run:
          name: Install CLI Vercel
          command: 'sudo npm install -g vercel'
      - attach_workspace:
          at: .
      - run:
          name: Vercel Prod Deploy
          command: 'vercel --prod -n $VERCEL_PROJECT_NAME --token=$VERCEL_TOKEN --yes'
      - run:
          name: Vercel logs
          command: 'vercel --logs'
workflows:
  version: 2
  deploy-reactapp:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - develop
      - vercel-deploy:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - develop
